# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioPlayer

  pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'

  target 'AudioPlayer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'AudioPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AudioPlayer-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AudioPlayer-tvOS


end
